### ISSUE TITLE
Extend markdown-extensions

### ISSUE THREAD

**Issue by matiassingers** [sindresorhus/text-extensions#2]
[markdown-extensions](https://github.com/sindresorhus/markdown-extensions)

To ensure both are kept up-to-date.

**Comment by sindresorhus** [comment]
I considered it, but they're both JSON files, so not worth the trouble. And I want to keep them JSON files so they can be used in any environment, like eg Ruby/Python/Java.

**Comment by matiassingers** [comment]
Ah true, extending JSON files is a bitch.

:+1:
